config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "boards#index"

  # resources :events
  resources :boards do
    post :sort, on: :collection
  end
  resources :cards do
    post :sort, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < Event
  validates :title, presence: true
end

app/models/card.rb
class Card < Event
  validates :title, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_list scope: [:parent_id, :type]
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json, :js

  helper_method :turbo_frame_request_id
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  protect_from_forgery except: :sort
  before_action :set_board, except: [:index, :new, :create, :sort]
  # respond_to :turbo_stream, only: [:create]

  def index
    @boards = Board.order(position: :asc)
    respond_with(@boards)
  end

  def show
  end

  def new
    @board = Board.new
    respond_with(@board)
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      respond_to :turbo_stream
    else
      respond_with(@board)
    end
  end

  def update
    @board.update(board_params)
    redirect_to boards_path
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  def sort
    if params[:item].present?
      @board = Board.find_by(id: params.dig(:item, :send))
      @board.insert_at(params.dig(:item, :position)&.to_i) if @board
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :type, :position)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery except: :sort
  before_action :set_card, except: [:index, :new, :create, :sort]
  before_action :set_board, except: :sort

  def index
    @cards = Card.where(parent_id: @board.id).order(position: :asc)
    respond_with(@cards)
  end

  def show
  end

  def new
    @card = Card.new
    @card.parent_id = @board.id
    respond_with(@card)
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      respond_to :turbo_stream
    else
      respond_with(@card)
    end
  end

  def update
    @card.update(card_params)
    respond_with(@card)
  end

  def destroy
    @card.destroy
    redirect_to boards_path
  end

  def sort
    if params[:item].present?
      position = params.dig(:item, :position)&.to_i
      @card = Card.find_by(id: params.dig(:item, :send))
      @card.insert_at(position + 1) if @card
    end
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def set_board
    board_id = params[:board_id] || params.dig(:card, :parent_id) || @card&.parent_id
    @board = Board.find(board_id)
  end

  def card_params
    params.require(:card).permit(:title, :type, :position, :parent_id, :note)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  respond_to :turbo_stream, only: [:create, :update, :destroy]

  def index
    @events = Event.all
    respond_with @events
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      respond_with(@event)
    end
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy!
    respond_with(@event)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/edit.html.slim
= turbo_frame_tag turbo_frame_request_id
  == render "form"

app/views/application/new.html.slim
= turbo_frame_tag turbo_frame_request_id
  == render "form"

app/views/application/show.html.slim
= turbo_frame_tag turbo_frame_request_id
  == render "show"

app/views/boards/_form.html.slim
= simple_form_for(@board) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, label: false, placeholder: "New Board"

  .form-actions.d-flex.justify-content-between
    = f.button :submit
    = link_to :close, :back, class: "btn btn-dark ms-2"

app/views/boards/_show.html.slim
- board ||= @board
.card.w-25.lists.card-link-pop id=dom_id(board) data-id=board.id
  .card-header.d-grid.cursor-move
    = turbo_frame_tag dom_id(board) do
      .d-flex.justify-content-between
        h5.card-title
          = board.title
        .dropdown
          .dropdown-action[type="button" data-bs-toggle="dropdown" aria-expanded="false"]
            svg.icon.icon-tabler.icons-tabler-outline.icon-tabler-menu[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
              path[stroke="none" d="M0 0h24v24H0z" fill="none"]
              path[d="M4 8l16 0"]
              path[d="M4 16l16 0"]
          ul.dropdown-menu.dropdown-menu-end.dropdown-menu-demo.dropdown-menu-arrow
            li = link_to "Edit", edit_board_path(board), class: "dropdown-item"
            li = link_to "Delete", board_path(board), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "dropdown-item"

  .card-body
    = turbo_frame_tag "cards", src: cards_path(board_id: board)
    = turbo_frame_tag "new_card" do
      = link_to new_card_path(board_id: board), class: "text-muted links" do
        .card.rounded-pill.card-link
          .card-body
            .text-center
              | add new card

app/views/boards/create.turbo_stream.slim
= turbo_stream.append controller_name do
  == render "show", board: @board

= turbo_stream.update "new_frame" do
  |

app/views/boards/index.html.slim
#boards.boards.gap-2.py-4(
  data-controller="sortable"
  data-sortable-url="#{sort_boards_path}"
)
  = turbo_frame_tag "new_frame"
  - @boards.each do |board|
    = render "show", board: board

app/views/boards/new.html.slim
= turbo_frame_tag turbo_frame_request_id
  .card.lists
    .card-body
      == render "form"

app/views/cards/_form.html.slim
.card.mb-2
  .card-body
    = simple_form_for(@card) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      .form-inputs
        = f.input :title, label: false, placeholder: "Title"
        = f.input :note, label: false, placeholder: "Note"
        = f.input :parent_id, as: :hidden, label: false, placeholder: "Note"

      .form-actions.d-flex.justify-content-between
        = f.button :submit
        = link_to :close, :back, class: "btn btn-dark ms-2"

app/views/cards/_show.html.slim
- card ||= @card
= turbo_frame_tag dom_id(card), data: { id: card.id } do
  .card.mb-2.handle.shared
    .card-body
      .d-flex.justify-content-between
        h3.card-title.mb-1
          = card.title
        .dropstart
          .dropdown-action[type="button" data-bs-toggle="dropdown" aria-expanded="false"]
            svg.icon.icon-tabler.icons-tabler-outline.icon-tabler-pencil[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
              path[stroke="none" d="M0 0h24v24H0z" fill="none"]
              path[d="M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4"]
              path[d="M13.5 6.5l4 4"]
          ul.dropdown-menu.dropdown-menu-end
            li = link_to "Edit", edit_card_path(card, board_id: @board), class: "dropdown-item"
            li = link_to "Delete", card_path(card, board_id: @board), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "dropdown-item"

      .small.card-text.text-wrap.text-muted
        = card.note

app/views/cards/create.turbo_stream.slim
= turbo_stream.replace dom_id(@board) do
  == render "boards/show", board: @board

app/views/cards/index.html.slim
= turbo_frame_tag "cards" do
  div data-controller="sortable" data-sortable-url=sort_cards_path data-sortable-handle=".handle"
    - @cards.each do |card|
      = render "show", card: card

app/views/events/_event.html.slim
= turbo_frame_tag dom_id(event) do
  .card.card-link.card-link-rotate
    .card-body
      p
        strong Title:
        =< event.title
      p
        strong Note:
        =< event.note
    .card-footer.p-2
      .d-flex
        .ms-auto
          = link_to [:edit, event], class: "me-2"
            svg.icon.icon-tabler.icons-tabler-outline.icon-tabler-pencil[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
              path[stroke="none" d="M0 0h24v24H0z" fill="none"]
              path[d="M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4"]
              path[d="M13.5 6.5l4 4"]
          = button_to event_path(event), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "text-danger ms-auto"
            svg.icon.icon-tabler.icons-tabler-outline.icon-tabler-trash[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"]
              path[stroke="none" d="M0 0h24v24H0z" fill="none"]
              path[d="M4 7l16 0"]
              path[d="M10 11l0 6"]
              path[d="M14 11l0 6"]
              path[d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"]
              path[d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"]

app/views/events/_form.html.slim
= simple_form_for(@event) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :note

  .form-actions
    = f.button :submit

app/views/events/destroy.turbo_stream.slim
= turbo_stream.remove @event

app/views/events/index.html.slim
= turbo_frame_tag "events", target: "_top" do
  p style="color: green" = notice

  h1 Events

  .row.row-cards
    .col-md-3
      = turbo_frame_tag "new_frame"
    - @events.each do |event|
      .col-md-3
        == render "event", event: event

app/views/events/show.html.slim
= turbo_frame_tag "events" do
  == render @event

  div
    => link_to "Edit this event", edit_event_path(@event)
    '|
    =< link_to "Back to events", events_path

    = button_to "Destroy this event", @event, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title DemoApp
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"

  body.px-6.layout-fluid data-controller="application"
    .page
      .page-wrapper
        .page-header.d-print-none
          .container-xl
            .row.g-2.align-items-center
              .col
                .page-pretitle
                  |  Overview
                h2.page-title.text-uppercase
                  = controller_name
              .col-auto.ms-auto.d-print-none
                .btn-list
                  span.d-none.d-sm-inline
                    = link_to url_for(action: :new), data: { turbo_frame: "new_frame" }, class: "btn btn-primary" do
                      svg.icon[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"]
                        path[stroke="none" d="M0 0h24v24H0z" fill="none"]
                        path[d="M12 5l0 14"]
                        path[d="M5 12l14 0"]
                      |  Add #{controller_name.singularize.humanize}
        .page-body
          .container-xl.overflow-x-auto
            / = turbo_frame_tag "first_frame"
            = yield